# Generated by Django 2.1.7 on 2019-05-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0005_auto_20190430_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.AutoField(primary_key=True, serialize=False)),
                ('asientos', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Internacionale')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-id_pasaje'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('documento', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['-id_pasajero'],
            },
        ),
        migrations.AddField(
            model_name='pasaje',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Pasajero'),
        ),
    ]
