# Generated by Django 2.1.7 on 2019-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasaje',
            name='asientos',
        ),
        migrations.RemoveField(
            model_name='pasaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='asientos',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fecha',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
