# Generated by Django 2.1.7 on 2019-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190502_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='asientos',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='fecha',
        ),
    ]
