# Generated by Django 2.1.7 on 2019-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190502_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='asientos',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
