# Generated by Django 2.1.7 on 2019-05-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_pasajero_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='asientos',
        ),
    ]
