# Generated by Django 2.1.7 on 2019-05-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190502_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='fecha',
        ),
    ]
