# Generated by Django 2.1.7 on 2019-05-02 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_pasajero_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 5, 2, 16, 49, 28, 8426, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
