# Generated by Django 2.1.7 on 2019-05-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_pasajero_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='lugar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='package.Internacionale'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='pasajero',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Pasajero'),
        ),
    ]
