# Generated by Django 2.1.7 on 2019-05-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20190503_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='asientos',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
