# Generated by Django 2.1.7 on 2019-05-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20190503_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Internacionale'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Pasajero'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='asientos',
            field=models.SmallIntegerField(),
        ),
    ]
