# Generated by Django 2.1.7 on 2019-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internacionale',
            fields=[
                ('id_internacional', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='projects')),
            ],
            options={
                'verbose_name': 'Internacional',
                'verbose_name_plural': 'Internacionales',
            },
        ),
        migrations.CreateModel(
            name='Nacionale',
            fields=[
                ('id_nacional', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='projects')),
            ],
            options={
                'verbose_name': 'Nacional',
                'verbose_name_plural': 'Nacionales',
            },
        ),
    ]
