# Generated by Django 2.1.7 on 2019-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190429_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacionale',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nacionale',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
